chopt: more checks and options
chopt checks against running instances and aborts the execution.
An installation of lsof is needed and added to orahost role.

The chopt execution could be forced with: -e forcechopt=yes

diff --git a/roles/oraswdb-install/tasks/install-home-db.yml b/roles/oraswdb-install/tasks/install-home-db.yml
--- a/roles/oraswdb-install/tasks/install-home-db.yml
+++ b/roles/oraswdb-install/tasks/install-home-db.yml
@@ -46,12 +46,24 @@
 # => use this method for all >= 11.2 (Doc ID 948061.1)
 # touch a statefile instead checking the logfile from chopt
 # we cannot use default/main.yml here. => complicated structure for 'enabled' 'disabled'...
+# check for running processes on $ORACLE_HOME/bin/oracle
+# 1st check for installed lsof, because systems could miss it...
 - name: install-home-db | Change Database options with chopt
   shell: |
+    set -eu
+    if lsof > /dev/null  2>&1 ; then
+      if lsof {{ oracle_home_db }}/bin/oracle > /dev/null 2>&1 ; then
+        echo "running Oracle processes found. Aborting chopt!"
+        exit 10
+      fi
+    else
+      echo "Please install lsof"
+      exit 9
+    fi
     {{ oracle_home_db }}/bin/chopt {{ item.state | replace(true, 'enable') | replace(false, 'disable') }} {{item.option}} \
     && touch {{ oracle_home_db }}/install/chopt_{{item.option}}_{{ item.state }}.state
   args: 
-    creates: "{{ oracle_home_db }}/install/chopt_{{item.option}}_{{ item.state }}.state"
+    creates: "{{ oracle_home_db }}/install/chopt_{{item.option}}_{{ item.state }}.state{{ choptcheck }}"
   with_items:
     - "{{oracle_EE_options}}"
   become: yes
